// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Day01Input$BsAoc2018 = require("./Day01Input.bs.js");

function getFinalFrequency(frequencies) {
  if (frequencies) {
    return frequencies[0] + getFinalFrequency(frequencies[1]) | 0;
  } else {
    return 0;
  }
}

console.log(getFinalFrequency(Day01Input$BsAoc2018.input));

exports.getFinalFrequency = getFinalFrequency;
/*  Not a pure module */
