// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var a = 1;

var b = 2;

var c = /* "a" */97;

var d = "d";

var e = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

exports.a = a;
exports.b = b;
exports.c = c;
exports.d = d;
exports.e = e;
/* No side effect */
